[project]
name = "proyecto-grupo-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
    "rich>=14.2.0",
    "ruff>=0.14.1",
]